// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ5kfxABgZbKfseA0OivcMlToC7BkhiFg',
    appId: '1:174021867373:web:9e25851eee6a532b878c64',
    messagingSenderId: '174021867373',
    projectId: 'doctor-appoitment-4b',
    authDomain: 'doctor-appoitment-4b.firebaseapp.com',
    storageBucket: 'doctor-appoitment-4b.firebasestorage.app',
    measurementId: 'G-DC0BEYS88D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaLDtc-wxwoqDQGuIW2XBDa_MqxiAKREE',
    appId: '1:174021867373:android:e5d207f3df822c55878c64',
    messagingSenderId: '174021867373',
    projectId: 'doctor-appoitment-4b',
    storageBucket: 'doctor-appoitment-4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNgl-RumM247dfOv7aH4FT2vv-5ciqNls',
    appId: '1:174021867373:ios:d4a48b90291ceae0878c64',
    messagingSenderId: '174021867373',
    projectId: 'doctor-appoitment-4b',
    storageBucket: 'doctor-appoitment-4b.firebasestorage.app',
    iosBundleId: 'com.example.sistemaCitasMedicas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNgl-RumM247dfOv7aH4FT2vv-5ciqNls',
    appId: '1:174021867373:ios:d4a48b90291ceae0878c64',
    messagingSenderId: '174021867373',
    projectId: 'doctor-appoitment-4b',
    storageBucket: 'doctor-appoitment-4b.firebasestorage.app',
    iosBundleId: 'com.example.sistemaCitasMedicas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ5kfxABgZbKfseA0OivcMlToC7BkhiFg',
    appId: '1:174021867373:web:15407c03518b1c81878c64',
    messagingSenderId: '174021867373',
    projectId: 'doctor-appoitment-4b',
    authDomain: 'doctor-appoitment-4b.firebaseapp.com',
    storageBucket: 'doctor-appoitment-4b.firebasestorage.app',
    measurementId: 'G-K9CQ8K6BP9',
  );
}
